name: Code style & compatibility

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, php: 8.2 }

    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

    - name: "Installing php"
      uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ matrix.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ matrix.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Run phpcs
      run: |
        vendor/bin/phpcs
