name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, php: 8.1 }
          - { os: ubuntu-latest, php: 8.2 }
          - { os: ubuntu-latest, php: 8.3 }
          - { os: ubuntu-latest, php: 8.4 }

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: "Installing php"
      uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # v2
      with:
        php-version: ${{ matrix.php }}
        extensions: curl,gd,mbstring,mysql,intl,xdebug
        coverage: xdebug
        tools: composer

    - name: Show PHP version
      run: php -v && composer -V

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ matrix.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ matrix.os }}-composer-


    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Run tests
      run: |
        export XDEBUG_MODE=coverage
        vendor/bin/phpunit
